routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function ()
{

Route::resource('/users', 'UsersController', ['except' => [
      'update', 'show']]);

Route::resource('/places', 'PlacesController', ['except' => [
      'update', 'show']]);

Route::resource('/place_categories', 'place_categoriesController');

Route::resource('/locations', 'LocationController');

});

Route::resource('users', 'UsersController', ['except' => [
     'create', 'destroy', 'index', 'store']]);

Route::resource('places', 'PlacesController', ['except' => [
     'create', 'destroy', 'index', 'store']]);
			

Route::post('admin/users/search', 'SearchController@search');

Route::post('admin/places/search', 'SearchController@searchplace');

Route::get('/rooms', 'RoomsController@indexrooms');

Route::get('place/{place}/rooms', [
        'as'   => 'rooms.index',
        'uses' => 'RoomsController@index'
    ]);

Route::get('place/{place}/rooms/create', [
        'as'   => 'rooms.create',
        'uses' => 'RoomsController@create'
    ]);
Route::post('place/{place}/rooms', [
        'as'   => 'rooms.store',
        'uses' => 'RoomsController@store'
    ]);
Route::get('place/{place}/rooms/{room}', [
        'as'   => 'rooms.show',
        'uses' => 'RoomsController@show'
    ]);

Route::get('place/{place}/rooms/{room}/edit', [
        'as'   => 'rooms.edit',
        'uses' => 'RoomsController@edit'
    ]);

Route::put('place/{place}/rooms/{room}', [
        'as'   => 'rooms.update',
        'uses' => 'RoomsController@update'
    ]);

Route::delete('place/{place}/rooms/{room}', [
        'as'   => 'rooms.destroy',
        'uses' => 'RoomsController@destroy'
    ]);

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <title>Portail d'administration</title>
	    <link rel="stylesheet" href="/css/admin.css">
	    <!-- include libraries(jQuery, bootstrap) -->
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"></script> 
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script> 

<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">




	</head>
	<body>

	@if(Auth::User()->hasRole('admin'))
		<a href="{{ url('/logout') }}"
                      onclick="event.preventDefault();
                      document.getElementById('logout-form').submit();">
                             Se déconnecter
                </a>

       <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
              {{ csrf_field() }}
       </form>
        <br/>

		<a href="{{ route('users.index') }}"> Utilisateurs </a>
		<br/>

		<a href="{{ route('places.index') }}"> Lieux </a>
		<br/>

		<a href="{{ route('place_categories.index') }}"> Catégorie de lieux </a>
		<br/>

		<a href="{{ route('locations.index') }}"> Localisations </a>
		<br/>

		@endif

		<a href="{{ url('/home') }}" > Retour à l'accueil </a>
		<br/>
		<div class="main">



		    @yield('content')

		</div>
		<script src="/js/all.js"></script>
	</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link rel="stylesheet" href="/css/public.css">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Witnsee</title>

    <!-- Styles -->

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Witnsee
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Se connecter</a></li>
                        <li><a href="{{ url('/register') }}">S'enregistrer</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Se déconnecter
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- Scripts -->
    <script src="/js/all.js"></script>
    <script src="/js/app.js"></script>
</body>
</html>